### ISSUE TITLE
Payment reference number (pmt_reference)

### ISSUE THREAD

**Issue by mattiteraslahti** [maksuturva/magento_payment_module#1]
Maksuturva_Maksuturva_Model_MaksuturvaGatewayImplementation on line 176:
"pmt_reference" => ($order->getIncrementId() + 100),

Is there a good reason for adding +100 to the order increment id? It causes difficulties in targeting payments to orders in accounting. Could it be changed to:
"pmt_reference" => ($order->getIncrementId()),

**Comment by maksuturva** [comment]
The reference number must comply with the guidelines for a formal reference number issued by the Federation of Finnish Financial Services (FK, http://www.fkl.fi). The reference number must be at least 4 digits, the last of which is a check digit. 
(more: http://www.fkl.fi/en/material/publications/Publications/The_reference_number_and_the_check_digit.pdf or https://www.fkl.fi/teemasivut/sepa/tekninen_dokumentaatio/Dokumentit/kotimaisen_viitteen_rakenneohje.pdf)

Adding 100 to the id and adding the check digit in the end ensures that the reference number is at least four digits long. But if the web store ensures that the order numbers start at least from 100, you can of course alter the code as you suggested.

By default the module sets 
"pmt_orderid" => $order->getIncrementId()
so you can use pmt_orderid to match orders in Magento.
